apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jenkins
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - jenkins.istio.tech
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins
spec:
  gateways:
    - jenkins
  hosts:
    - jenkins.istio.tech
  http:
    - route:
      - destination:
          host: jenkins.jenkins.svc.cluster.local
          port:
            number: 80
